### ISSUE TITLE
Email for upcoming reboot

### ISSUE THREAD

**Issue by etoews** [getcarina/carina-emails#4]
We need to work up an email template for customer communication for the upcoming reboot. Suggestions and points to hit should go into comments on this issue.

Those suggestions and points should go into a pull request for an email template living in https://github.com/getcarina/carina-emails/tree/master/templates

/cc @mendeni @thomasem @jnoller @kimtryce @kenperkins @ktbartholomew @simonjj @leader716

**Comment by ktbartholomew** [comment]
I'll add the one-column template we have in this repo to our Mailchimp account, so whoever sends it can just use their WYSIWYG tool to add the appropriate body copy.

**Comment by etoews** [comment]
Remind users about setting [Restart policy](https://docs.docker.com/engine/reference/commandline/run/#restart-policies-restart) to `always` or `unless-stopped`.

**Comment by ktbartholomew** [comment]
This template has been added to Mailchimp as "simple one-column". The headline and body copy are all editable with Mailchimp's tooling.

![image](https://cloud.githubusercontent.com/assets/3018940/14332971/c3cea3ca-fc11-11e5-9b5d-bf49588c4cad.png)

**Comment by jnoller** [comment]
@kimtryce

**Comment by mendeni** [comment]
Here's the bug we're fixing:  https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19#.uqrp88h9d

**Comment by kimtryce** [comment]
@mendeni when do you want this to go out (what date)?

**Comment by mendeni** [comment]
We're planning to start reboots on Monday 4/11 @ 12:00 central.

It will take about 90 minutes from start to finish since we have to stagger the reboots to prevent power consumption issues.

If we could get the comms out today (4/7), it would give users ample time to check restart settings, etc.

We should also schedule maintenance on status.io.

**Comment by kimtryce** [comment]
Editorial eye: https://github.com/getcarina/carina-emails/blob/master/templates/carina-reboot

**Comment by kimtryce** [comment]
Let me know how it looks and I'll ship @jnoller @mendeni @everett-toews @ktbartholomew ^^

**Comment by thomasem** [comment]
Would it be worth it to communicate that users nodes will be unavailable for short periods of time throughout this process as we roll through rebooting infrastructure? The wording currently sounds like users' nodes will be down for an entire 90 minutes.

Also, I'd `s/instances/nodes/`

**Comment by kimtryce** [comment]
I can make adjustments.  Thanks Thomas for the edits.

**Comment by kimtryce** [comment]
@ktbartholomew I saw your comment.  Will change the text/hyperlink

**Comment by thomasem** [comment]
Thanks, @kimtryce!

**Comment by mendeni** [comment]
@kimtryce  Looks like a typo "has a bug a bug that affects"

**Comment by mendeni** [comment]
@kimtryce  Let's also change the reboot date/time to:
<strong>Tuesday, April 12 at Noon CST</strong>
